### ISSUE TITLE
RFE Sight >FIX - Show the X only when fix is open

### ISSUE THREAD

**Issue by rbossert149419** [rgleason/celestial_navigation_pi#118]
Windows 10 PC.  Cel Nav Version 51 beta

I've used this a couple times in the past couple days and when I open the FIX form it always shows some erroneous lat and longitude which I assume the fix form used to initialize a search with.   Note it is  
-30 and -49.7 minutes.  And I'm not sure where it picked up that number since I think the rest of Cel Nav plugin uses decimal degrees.  The third field that contains Error and some huge number makes it seem like it was supposed to initialize with decimal degrees?

Note the screen shot of "ship" position (lower left).  I setup my chart data to display degrees and decimal minutes (no seconds).  

The fix form works, but I have to first put initial lat and long.  Note the form shows, "initial" 2 times.  I presume one is initial lat and the second is Initial lon.   And I assume positive is North and East, negative is South and West.

Was the intention of the Fix form to use Boat Position for initial estimate of Fix?   And let the user adjust initial estimate as necessary before clicking "GO"?

![Image](https://github.com/user-attachments/assets/5b643365-ff07-4d41-9f33-c844f6b0181e)

**Comment by rgleason** [comment]
Almost a duplicate, same subject

https://github.com/rgleason/celestial_navigation_pi/issues/109#issuecomment-2787796835

**Comment by rbossert149419** [comment]
So, it is checking any Mark or waypoint that is on my charts?   For a 2 body fix, there is 2 intersections.  And I have a mark that is part of a route at S25 36.5 and E053 57.6.  It won't show up on the Mark and Track Manager because it is on the route only.  When I delete the route, OCPN will auto delete that waypoint (fairly new OCPN feature).  That Mark is 336 nm away from the southern/East intersection of the 2 body fix  I don't think I have anything closer (unless it is a not visible waypoint that is part of a not visible route.   I won't test by making visible all of my invisible routes).  I do have a mark that I dropped at N 43 08.4 and W 77 26.8 which is 6.9 nm away from the North/West intersection of the 2 body fix.

I see that Cel Nav plugin can display Lat and Lon into Degrees and decimal minutes.  That's good to know.

I would have thought FIX capability would start out with Boat Position as most likely starting point.  Initial selecting a waypoint is perfectly fine with me.  The boat moves, the mark stays put.  The waypoint should denote location where I assumed I took the sight.

I don't know if it is worth while fixing 2 minor issues.
(1)  the sign in front of minutes.  There should be a sign in-front of the decimal.
(2)  the form not showing which is initial Lat and Lon.

**Comment by stelian42** [comment]
The fix search starts from initial lat/lon, which are 0, 0 by default.

Celnav plugin does not know about routes or waypoints placed in main OpenCPN.

**Comment by rgleason** [comment]
Formatting?  Width?

**Comment by stelian42** [comment]
Yes, the label and width of the fields could use some love.

**Comment by rgleason** [comment]
Can this be closed now?

**Comment by rbossert149419** [comment]
Instead of defaulting with Lat 0 degree and lon 0 degree, is it simple change to initialize with Boat Position....at least the whole degree portion (ie skip the minutes or the decimal degrees)?  

Only Consider if it is a simple change.

**Comment by stelian42** [comment]
I have pushed some changes to git, including boat position and labelling and copy/paste ability. Please test.

**Comment by rgleason** [comment]
Stelian, this works better,  spacing is always difficult with those -1's etc.  I still don't know how to scale those for DPI and they seem to get truncated on high dpi screens.  It is a pita.  I wonder if we should let this go, but perhaps you can improve some of the spacing to tighten it up a bit.  I like the DR lat and DR long

![Image](https://github.com/user-attachments/assets/748afc5d-532a-4720-8a84-342789f2ebce)

**Comment by rbossert149419** [comment]
Please reopen.   The changes to the FIX form introduced a new problem.  Now every time you make 2 sights visible, the FIX routine is automatically run.   

Before, it only did a FIX if you selected the FIX form and Pressed GO.   Now, every time you make a sight Visible, a FIX is run.

**Comment by stelian42** [comment]
Rework pushed into git. Let me know if this is ok on Windows/MacOS screens.

**Comment by rgleason** [comment]
@stelian42  @rbossert149419  That did not deploy to [cloud](https://cloudsmith.io/~opencpn/repos/celestial-navigation-alpha/packages/)   because of the direct push to my improve branch.

**Comment by rbossert149419** [comment]
How about the workaround of making the sights unvisible and the X disappears

**Comment by rgleason** [comment]
Bob, 2.4.56 is building  and should land in C-S  beta,   add a search in the upper right  " 2.4.56  tarball"

https://cloudsmith.io/~opencpn/repos/celestial-navigation-alpha/packages/
https://cloudsmith.io/~opencpn/repos/celestial-navigation-beta/packages/

**Comment by stelian42** [comment]
I have NOT changed the way fix works, only the layout of the dialog so the items hopefully wouldn't be cropped.

**Comment by rgleason** [comment]
So where does this stand now?

**Comment by rbossert149419** [comment]
The Big Red X always showing is very annoying and it is wrong under many standard situations...A Fix is automatically Displayed when I make a sight visible.  If it is within 20 minutes, no problem.  But I can do a morning Sun sight (Sun rises in the east), then I create an afternoon Sun sight (sets in the west) 30-40 miles away.  The FIX will be wrong due to time difference.  But when I advance the first LOP by the distance I made in the direction I made it, the Fix would be ok, and called a Running Fix.  

I'd like to only display the FIX when I request it.  Not automatically.  Stellain suggested the GO button be the trigger to create the FIX.  And the simple solution for making that visible fix disappear would be making the Lines/CIrcle of Position invisible.

This could be an Enhancement.  I didn't realize the Big X was always somewhere on the Circle of Position.   The default 0-0 Lat and Long was out of the way.

**Comment by rgleason** [comment]
> And the simple solution for making that visible fix disappear would be making the Lines/CIrcle of Position invisible.

What do you mean by this?  Why not just have a button to turn the darn thing off?   "Fix OFF"

**Comment by rgleason** [comment]
So you want an  **_"0" Button_** that sets Lat=0 and Long=0?

**Comment by rgleason** [comment]
> Besides, offshore navigators do running fixes the majority of the time.
> The fix algorithm is wrong when the 2 or more lines of position are taken
> at different times.   You can do a fix with the 2 or more lines of position
> if the time difference between the first and last sight is less than 20
> minutes.

So do a DR shift.

**Comment by rgleason** [comment]
So how would you control it?  
You hit FIX and then 5 seconds later it defaults back?
I might want to get copy the lat long of fix before it goes back to 0-0!

**Comment by rgleason** [comment]
Wait for Bob's new Issue, then close this one.

**Comment by rbossert149419** [comment]
Please revert back to how it was with 0-0. The cosmetic formatting of field
widths are fine.

Is that ok?

**Comment by rgleason** [comment]
What is wrong with a ) Button?

**Comment by stelian42** [comment]
I would keep the position but modify the code to show the "X" only when the Fix dialog is opened. How is that ?

**Comment by rbossert149419** [comment]
I like what Stelian is proposing.  If the fix dialog form is open then the
X appears.  It sounds simple and user has control

**Comment by rgleason** [comment]
While discussing FIX  what about this idea?

RFE Sight >FIX - add Fix to DR angle & distance #126
https://github.com/rgleason/celestial_navigation_pi/issues/126

**Comment by stelian42** [comment]
I have implemented my proposed solution in git.

**Comment by rbossert149419** [comment]
Do I need to wait for a new version on cloudsmith?  Or is it there now

**Comment by rgleason** [comment]
You can check cs alpha but if stelian pushed directly to my repo i will have to bld it tonight. Sorry i am traveling today.

**Comment by stelian42** [comment]
@rgleason I thought I was clear yesterday or the day before when I was explaining why the push to Cloudsmith does not work, whatever method I use.

Just to prove you this, I just made a test commit, this time using a PR from my repo (https://github.com/rgleason/celestial_navigation_pi/pull/134). As you can see by yourself, there was no resulting build on cloudsmith-alpha.

It has to be **YOU** the one **merging** the commit, or **pushing** a commit in order to make the upload work.

**Comment by rgleason** [comment]
Thank you for trying again.  I agree it did not work.
Yes, I thought that was a "sometimes".  
I have been doing some research on this, as your merges should build and deploy to CS!
In any case, I'd like them to, so that is one goal.
As this would be much better and more convenient for everyone.

Right now I've incremented and pushed v2.4.57.0 up to my remote repository. and it should land in
cloudsmith/celestial-navigation-beta    then in the upper right hand box do a search on "2.4.57.0 tarball"
@rbossert149419

**Comment by rgleason** [comment]
![Image](https://github.com/user-attachments/assets/237cc8cb-4eb9-4db9-91b6-c3de874e3756)

**Comment by stelian42** [comment]
I have pushed again a small change to widen the Go button.

As for the Drift from the Boat, let's keep this separate in RFE #126

**Comment by rbossert149419** [comment]
There were 2 versions of 57.  I downloaded the larger one to my windows 10
PC.  It is working very nice.  Thank you very much.  I will download the
next version on my iMac.

**Comment by rgleason** [comment]
@rbossert149419  I think the distinction should be to use the most recent!!!  Don't bother with the older one.

**Comment by rgleason** [comment]
Closing
