### ISSUE TITLE
Moon Semi-Diameter and Horizontal Parallax used by Celestial plugin is off by up to +/- 8%.  Change Moon SD/HP to approach Nautical Almanac precision.

### ISSUE THREAD

**Issue by rbossert149419** [rgleason/celestial_navigation_pi#25]
**Problem**:  The Moon Semi-Diameter and Horizontal Parallax is used to determine Observed Altitude (Ho).  In the plugin, it is a constant based on average SD and the relationship that SD=.27346*HP.  The SD and HP used by Nautical Almanac varies up to +/- 8% from the average.  

**Impact**:  In 2 moon sight reduction examples, the Plugin’s Observed Altitude (Ho) was 1 to 4.7 arc-minutes too small and the Estimated Position (single body sight) was off by 1 to 4.7 nautical miles.  The proposal substantially reduces the Observed Altitude (Ho) variances between Nautical Almanac and Celestial Plug-in.

**Request**:  The plugin to use a more precise Moon SD and HP to approach the Nautical Almanac precision.  SD and HP for Sun, Mars, Venus remain unchanged, for now.  The Nautical Almanac for table based sight reductions has Moon’s SD is fixed for 3 Days, and Moon’s HP identified per whole hour.   NA documents a sight reduction based on formulas (page 280-281), and only requires getting the Moon’s hour based HP.  There is a free software product that doesn’t need internet to reduce sights and has precise Moon SD/HP.  OpenCPN can match that product.
	The Plugin’s Sight Properties and Calculation form shows the formulas and intermediate calculations starting with Measured Altitude (Hs) and ending with Observed Altitude (Ho).  The calculation form is useful.  It should be kept current when the plugin changes.

**Current and Proposed.**  The Moon Semi-Diameter used by the Plug-in is documented to be 15.5’ constant (per Sight Properties/ Calculations form).  But in the plugin’s Limb correction, the constant 0.2591° (15.546 arc-minutes) is used.  That value is closer to the average Moon SD (15.53872’).  HP’s 56.9’ / .94833° value under “Almanac Data for Moon”, is changed to .9475° when calculating Moon’s parallax correction.  The plugin’s HP constant is based on SD = .27346HP.   The Nautical Almanac’s confirms “SD = .2724*HP” (page 285, step 5).  NA adds Earth Oblateness (OB) to the parallax equation (page 280, step 4).  The solution might be to extract a HP data (not use average) from a source of record, and then calculate SD (page 280, step 5).  ADD OB equation to the Parallax calculation for the moon only

**Algorithm and Code (updated 1/26/2025)**
 Celestial Tools a software product owned by America's Boating Club (aka US Power Squadrons) uses a version of Jan Meeus algorithms documented in Chapter 25 of his 1991 book "Celestial Algorithms".  I tested it on my PC.  The Moon SD and HP output is within .1' of Nautical Almanac's version of truth.  I received part of the code (written in C# aka C sharp).  The code sent to me DOES NOT include what is necessary to compute SD and HP.  It does show how the developer went about Moon's position.  The code actually follows Meeus's book pretty closely.  The developer will send more code of specific functions if necessary.  It was programmed in VB and the developer has been converting it bit by bit to C sharp over time.

As a workaround for the code's missing SD/HP calculation details, I want to send a spreadsheet (Apple Numbers...I can export to powerpoint if you don't have a Mac) that shows the full computations (including full tables) and explanation.  It includes 7 test case worksheets from 1992, 2001 to 2025.  GitHub doesn't seem to allow me to update NUMBERS (just PDF).  So, I'll try to email the spreadsheet.  It isn't large.  You'll want to review the spreadsheet cells which are formulas.  The worksheet includes everything.  For this problem, you only need the cells pertaining to SD and HP.

Each Test Case is a worksheet.  The input to each worksheet (Julian Date (Delta_T should be included in the Julian Date).  The output is HP, SD, and Ecliptic Latitude and Longitude, and Equatorial Latitude and Longitude assuming a constant for epsilon (Earth Tilt) and Longitude Nutation (Earth wobble along the spinning axis).  If you need it, I'm confident I can work it out from Meeus's book.

**Attachment**.  Analysis of the impact and Examples included as attachment.

[CTSRFMoonFunctions.txt](https://github.com/user-attachments/files/18551652/CTSRFMoonFunctions.txt)

[Open CPN Celestial Plugin Moon Semi-Diameter:HP accuracy issue PDF.pdf](https://github.com/user-attachments/files/18470224/Open.CPN.Celestial.Plugin.Moon.Semi-Diameter.HP.accuracy.issue.PDF.pdf)

**Comment by rgleason** [comment]
Wow. This is a gift. Thank you. Hopefully we will find a good programmer.

You advise: 

> There is a free software product that doesn’t need internet to reduce sights and has precise Moon SD/HP. OpenCPN can match that product.

Do you have the name for this product?  Perhaps we can get the tables from that?

**Comment by rbossert149419** [comment]
Rick,

The product is owned by United States Power Squadron / America's Boating
Club.  I have a contact in their Offshore Navigation Education department.
I'll see what options are available.  Did the author of the celestial
navigation plugin get GHA, DEC, SHA tables from USNO Astronomical
Applications website (under Celestial Navigation Data) or the ADMIRALTY
(UK)?

Bob Bossert

**Comment by rgleason** [comment]
Dear Bob,
I do not recall, but the last time a very capable fellow updated and improved our accuracy with new tables and I think I added all of this information in the manual. Which I worked on quite a lot. It is probably not up to standards but it is our attempt at honoring this still very useful information and craft.

The manual format has changed and I did not have complete control over that, but I think the guys did a pretty good job transferring it.  It is housed in github now and not opencpn.wiki.  I can still edit it and so could you if you find the need or desire.

Out of curiosity, are you an OpenCPN user?  https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn
Here is the plugin list https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:manual_basic:set_options:plugin_manager  Celestial Nav is under Navigation

Here is the manual https://opencpn-manuals.github.io/main/celestial_navigation/index.html

**Comment by rbossert149419** [comment]
Thanks.   I'll review it.

Yes, I am an OpenCPN user.  And I am a Navigation teacher.....Right now,
I'm teaching Offshore navigation including Celestial Navigation.   I like
to include Open CPN in all of my classes.  Strategy being "do it
traditionally" followed by doing it with OpenCPN.

**Comment by rgleason** [comment]
I have a sextant, and after all these years working on Opencpn including the Cel_Nav plugin, I feel like I could learn it reasonably quickly, but I have never just sat down and figured it out. Too much else going on,,,

**Comment by rbossert149419** [comment]
The product, "Celestial Tools" is copyright and belongs to America's
Boating Club.  They are willing to share the code for the algorithms that
are common functions like SD, HP, etc.  They sent me a 6 page text file
that included their Greenwich function, Julian date function, and Moon
function.    Written in Microsoft C#.  The code is documented, readable.
The Moon function, which includes SD and HP is based on Jean Meeus in
Astronomical Algorithms Chapter 45 Position of the Moon.  The process they
use is to start with Time (like PC or watch time) convert to Greenwich (UT)
then convert to Julian Date and calculate using Julian.

**Comment by rgleason** [comment]
@rbossert149419  Bob that is great, and it is C++

**Comment by rbossert149419** [comment]
C# (aka C sharp).  Different, but many similarities to C++, both originate
from C.   I can send you the code's text now.   Or, wait until you are
ready.  Meanwhile, I think I'll continue reviewing the code (compare code
to Jean Meeus's book where a lot of it comes from).  It could help the
developer in unit testing.

I have a question on the Plug-in's Line of Position plot.  I read the user
documentation from the link, and I'd like to test my understanding about
how the Celestial Plug in LOP was determined.   It doesn't need the DR/Fix
(or boat location).  If DR changes, Plot remains constant.   It is based on
Ho and the GP of the body at the time the sight was taken.  And somehow
solving a Nautical Triangle with Ho (or 90 - Ho, Co-Ho) and GP as knowns.
What algorithm does it use?  I don't see an issue, just seeking to
understand.

Thanks

**Comment by rgleason** [comment]
Jean Meeus's name is familiar.  How big is the code when zipped?  You can add a zip file to these comments. That might be a good way to do it.

**Comment by rgleason** [comment]
From Bob's 2/6/25 email.
.. spreadsheet that demonstrates the Moon SD/HP algorithm with test cases.  In all of the test cases, the algorithm worked quite well.

From Bob's 2/8/25 email

> I have a C++ program that calculates only Moon Semi-Diameter and Parallax.  I tested it with the same examples as the spreadsheet I sent.  The spreadsheet  scope was bigger.  It completely calculates the moon's position as well as SD and Parallax.  And that goes beyond the problem I'd like to have fixed.  The plug in needs to be upgraded to use this program's parallax and semi-diameter rather than use an average semi-diameter and parallax.  Thus the C++ program is limited to Moon Semi-Diameter and Parallax.
> 
> There are a couple additional things I could do.....I used long double for most of the non integer numbers.  I can change to double....Double should work fine since we only need to meet Nautical Almanac standard precision (0.1 minutes).  
> 
> My program currently has Main() where I input Julian date (for key test data).  Within Main(), I do have some equations that might already exist in the plugin code for other purposes.  And from Main(), there is a simple function I wrote that does modulo on Large Degree values that need to be rounded down to between 0-360 degrees.   Then Main() calls my key function which calculates Distance from Earth to Moon (km) which changes enough in an hour to have an impact on Parallax and Semi-Diameter.  For our needs, Semi-Diameter and Parallax is based solely on this distance by the way.  The last part of Main() then calculates Semi Diameter and Parallax based on Distance.


Bob's email  2/9/25

> Thanks for offering to reach out to Sean Depagnier for his help to integrate this and another piece of C++ code that I'll send to you.  I bet he can make the coding changes quick.  Hopefully he is happy with this code.  Please let him know that, i'll be very pleased to test.  
> 
> Attached is my C++ source code for Moon Semi-Diameter and Parallax.  There is a self contained function that calculates Earth-Moon Distance using time dependent tables and equations.  The function's input is TT (Julian Date converted to Y2000 epoch century).  I suspect the plug in already calculated TT and can feed that as input to the function.
> 
> The function's output is Distance (in km).   Then there are 2 simple 1 line equations in Main()  that he can use to replace his existing 2 equations for Semi-Diameter and Parallax.  This code's Semi-Diameter and Parallax are in arc-minutes (to match Nautical Almanac), although he might want them in degrees.  Either way works for me.
> 
> I made comments in the code and I kept the trace statements to output intermediate and final results to the terminal.  I expect the output statements will be commented out.
> 
> You could send him my issues documentation for background of various bugs and suggested improvements.
> 
> I'm also attaching an Apple NUMBERS spreadsheet that was my pilot (if he needs it in excel, I can convert and resend).  The worksheets show my unit test script and results.

[Moon Parallax and SemiDiameter rev1.cpp.txt](https://github.com/user-attachments/files/18742521/Moon.Parallax.and.SemiDiameter.rev1.cpp.txt)

**Comment by rgleason** [comment]
Bob,   Povl Abrahamsen, 2/26/2017  did the [Calculation & Accuracy: Plugin Improvements](https://opencpn-manuals.github.io/main/celestial_navigation/index.html#_calculation_accuracy_plugin_improvements)  

He writes 

transform_star.cpp has been written by me, using equations from the [US Naval Observatory Circular No. 179](https://www.usno.navy.mil/USNO/astronomical-applications/publications/Circular_179.pdf)

    epv00.cpp comes from the SOFA library http://www.iausofa.org/, with a wrapper function written by Povl Abrahamsen.

Also we would like to acknowledge the use of the SOFA function and library. See [Article: Earth Rotation and Equatorial Coordinates](https://opencpn-manuals.github.io/main/celestial_navigation/index.html#_article_earth_rotation_and_equatorial_coordinates) below for general information about the error.

**Comment by rgleason** [comment]
Bob,  As I recall, I would have to look into it further, but some part of this was not done.

> I have a question on the Plug-in's Line of Position plot.  I read the user
> documentation from the link, and I'd like to test my understanding about
> how the Celestial Plug in LOP was determined.   It doesn't need the DR/Fix
> (or boat location).  If DR changes, Plot remains constant.   It is based on
> Ho and the GP of the body at the time the sight was taken.  And somehow
> solving a Nautical Triangle with Ho (or 90 - Ho, Co-Ho) and GP as knowns.
> What algorithm does it use?  I don't see an issue, just seeking to
> understand.

I believe Sean wrote the fix part. He is a math genius I think.
I found this note at the bottom of [my old tests. ](https://opencpn-manuals.github.io/main/celestial_navigation/index.html#_testing_of_celestial_navigation_again)

> NOTE
> The altitude & azimuth given with the “FIND” button is without the  Parameter’s Tab corrections, so it will not be as accurate as an actual  Sight.

**Comment by rgleason** [comment]
What is this?

> There is a free software product that doesn’t need internet to reduce sights and has precise Moon SD/HP. OpenCPN can match that product.

**Comment by rbossert149419** [comment]
Celestial Tools.  The author did it for America's Boating Club (U.S Power
Squadrons).

The code I supplied matches the precision that the program does for SD and
HP (when he sent me a copy of part of his C# program, I knew immediately
where he got the algorithm from).  And, the code I gave you matched
very nicely the Nautical Alamanac data for the sample data I used from 200x
to 2025.  So, my C++ program will fix the biggest problem with Celestial
Nav's Plug in for the Moon Position.

**Comment by rgleason** [comment]
[Open.CPN.Celestial.Plugin.Moon.Semi-Diameter.HP.accuracy.issue.pdf](https://github.com/user-attachments/files/18751089/Open.CPN.Celestial.Plugin.Moon.Semi-Diameter.HP.accuracy.issue.pdf)

[Moon Parallax and SemiDiameter rev1.cpp.txt](https://github.com/user-attachments/files/18751090/Moon.Parallax.and.SemiDiameter.rev1.cpp.txt)

[Position of Moon EXEL.xlsx](https://github.com/user-attachments/files/18751093/Position.of.Moon.EXEL.xlsx)

**Comment by stelian42** [comment]
FWIW, in case someone else reads this thread at a later point, there is a small error in _Moon Parallax and SemiDiameter rev1.cpp_ posted eariler:
`for (int i = 0; i < 61; i++) {`
should read:
`for (int i = 0; i < 60; i++) {`
otherwise random results can be seen sometimes (depends on how memory is allocated inside the program)

I am currently working to include this code in the plugin so we will get better Moon SD/HP corrections.

**Comment by stelian42** [comment]
And another error:
`+ 175 * sin( (a2 + mf) * M_PI/180)`
should read
`+ 175 * sin( (a1 + mf) * M_PI/180)`

**Comment by rbossert149419** [comment]
Thanks for catching my errors.  Right now  I’m revalidating against J Meeus
book

and I found another error of mine…..There is no additional adjustments to
sigma_r (line 145 to 150). These  are The adjustments for Venus and
flattening of the earth, adjustments for sigma_b (longitude in ecliptic
coordinate system)

I’m so sorry about that!   I missed that when I tested against J Meeus test
case example.  I’ll upload part of J Meeus pages on moon position as
evidence, and update my MOON POSITION spreadsheet

Bob Bossert

**Comment by stelian42** [comment]
Reading the Meeus page 342 (https://auass.com/wp-content/uploads/2021/01/Astronomical-Algorithms.pdf) states indeed that additives are only for sigma_l and sigma_b, not sigma_r !

**Comment by rbossert149419** [comment]
Yes, that’s what I said last night.  The lines of code that have those
additives can be deleted.  My mistake

**Comment by stelian42** [comment]
I incorporated @rbossert149419 's code into the plugin, this is PR https://github.com/rgleason/celestial_navigation_pi/pull/55

This should fix this issue.

Unfortunately I cannot build the plugin for MacOS, so we'll have to wait for @rgleason to return for testing.

**Comment by rbossert149419** [comment]
Did you change the calculation screen to show the new Ho, SD and HP?    I
still see the old Hp and SD values which were constants

**Comment by stelian42** [comment]
This change is not yet merged and build, so you do not have it yet in the plugin you downoladed yesterday. As I said we have to wait for Rick's return for rebuild.

**Comment by rgleason** [comment]
Stelian, Both of us can make a Pull Request from your branch into my branch "improve". Then I believe that I sent you an invitation to be a collaborator in my celestial navigation repository which gives you rights to merge the PR.  Then the CI continuous integration process will run using github, circleci for building, cloudsmith for storage and deployment.

You will find the tarballs and metadata files that have been built and deployed in cloudsmith celestial-navigation-alpha, celestial-navigation-beta and ocassionally celestial-navigation-prod (when committed, version tagged, and pushed  "git push --tags origin master").  I look at when the builds were done and the version to determine which cloudsmith repos they landed in.

Bob can download the appropriate built tarball from that repo in order to test.

**Comment by rgleason** [comment]
https://github.com/rgleason/celestial_navigation_pi/pull/55#issuecomment-2695527999

**Comment by rgleason** [comment]
Bob and Stelian, let me know when we can Close this please. Perhap best to close after Bob tests it.

**Comment by rbossert149419** [comment]
Do we have the latest version to test.  A couple small problems Stelian
fixed after you built.  And The calculation form needs to be updated with
the SD, parallax, and Ho

Bob

**Comment by stelian42** [comment]
@rgleason CI doesn't seem to upload packages, cloudsmith-upload.sh says 
`Cannot deploy to cloudsmith, missing $CLOUDSMITH_API_KEY`

**Comment by rgleason** [comment]
Stalian,  Is this problem occuring to Pull Requests which have been merged into the rgleason/celestial-navigation/improve branch? 

I will check this out and come back here.

**Comment by rgleason** [comment]
It looks like #61 worked and all builds were successful.  See the green check mark?  Click or right click on it and all the builds will be listed.  If there is an X by one of those builds you should be able to drill down and click on it and go to the circleci debug output (sometimes I have to search ctrl-f and enter "error" to find the problem, but most of the time the failing step is shown with output debug reports that indicate the problem.

As I said all the builds worked for #61   Good job @stelian42 Stelian!  now @rbossert149419 can download the most recent tarball from the cloudsmith alpha or beta directory and test it.

**Comment by rbossert149419** [comment]
Been Testing the solution.  

It is looking quite good.  for 2025, the SD and HP average difference between Nautical Almanac and Cel Nav Plugin is almost 0.  The standard deviation of the difference is about .1 minutes.  80-90 percent of the observations were either 0 or +/- .1 minutes different from Nautical Almanac.  And for the 48 observations I randomly selected in 2025, the largest difference from Nautical Almanac was .2 minutes.  

The next is excellent and surprising news.  Between this code, changing the significant digits to 4 or 5 digits, and maybe something Stelian did in the process, the 2025 Cel Nav GHA and Dec mean difference from nautical almanac is 0, and the standard deviation is .1 minutes.  In addition, only 4% of the GHA observations were greater than +/- .1 minute different from Nautical Almanac.  It is back to where it used to be 10 years ago.  Not sure how that happened, but that's a win.

I'll continue my testing tomorrow.  

Great Job, Stelian!

**Comment by rgleason** [comment]
Great job you guys. Is this Issue completed now. Can it be closed?

**Comment by rbossert149419** [comment]
Almost done testing.  Plan to be done Thursday

**Comment by stelian42** [comment]
Thanks for the testing.

_and maybe something Stelian did in the process, the 2025 Cel Nav GHA and Dec mean difference from nautical almanac is 0_

The reason is probably that I fixed the deltaT calculations which were slightly wrong for the current years (2010+).

**Comment by stelian42** [comment]
For 2024 it was returning 39.98, for 2025 40.35 seconds

With the new version it is returning 69.2 and 69.1 seconds (real observed values here from IERS)

Same kind of error for future observations: for 2050 old version returned 49.6, current version returns 93.

The reason of the difference is that Meeus original formulas proved wrong for 2000+. At some point Sean probably saw this, and "corrected" it, and introduced a new error in the code. The new version uses the new formulas from https://eclipse.gsfc.nasa.gov/SEcat5/deltatpoly.html for future years (formulas are used when observed/next future previsions from IERS are no longer available).

**Comment by rbossert149419** [comment]
Do you think it is useful to output these intermediate variables on
calculation form?   It could help to detect which equations need to be
updated in future years.   I was thinking delta T, inclination of earth’s
axis of rotation, ecliptic coordinates, nutation, obliquity, etc.

The reason is that this project started when I noticed moon sd and  hp were
constants and lucky they were output on calculate form

There is an new issue about improving calc form

Bob

**Comment by rbossert149419** [comment]
Stelian,

I'm testing the following.  Please let me know where I went wrong.
UT Date and Time.   Jan 25, 2025 10am.  to that I add Delta T, 69.2
seconds.  That makes it Jan 25 2025 10:01:09.2 AM.   I run it to a julian
date calculator and i get 2460700.917468
I run that JD date through the Meeus algorithm (excel and my version of C++
which I fixed based on the fixes you found).   I get HP 55.71839276, and SD
15.18159214.   the nautical almanac for that UT time is HP 55.7, and SD
15.2.   Which after rounding to .1 minute is exact match.

When I enter the data into open cpn plug in, I get HP 55.8555 and SD
15.2152 (from Calculations form).  Open CPN plugin HP and SD is slightly
higher.

Thanks,
Bob

**Comment by stelian42** [comment]
Bob,

deltaT for Jan 2025 is 69.1 not 60.2

**Comment by rbossert149419** [comment]
I just retested SD/HP using my Meeus algorithm spreadsheet where I had about a dozen examples of 2024, 2025, and some historic dates after 2001.  The purpose of that spreadsheet was to prove to me that the 1996 Meeus algorithm still worked (Celestial Tools program seemed to use it when I read some of it's code).  The examples matches both the algorithm and the Nautical Almanac for SD and HP.  I then checked 5 specific Jan 2025 dates on my Statistical Analysis spreadsheet (the spreadsheet has 49 random dates and times that spread evenly across 2025.  These numbers were slightly better than I reported last night.  5 dates (SD and HP) or 10 observations.  9 had 0 difference from Nautical Almanac.  Only 1 observation was off by .1  minute.  

The 10 observations did not seem to improve GHA and Dec although I was comparing to nautical almanac which only has .1 minutes precision.  Perhaps the time zone didn't impact Lat/Lon position of the moon?  

Any idea where the time zone issue would make an affect....Sun, Stars, Planets?  What issue have I missed testing?

Later on, I'll update my test scripts with actual results.  And will be very happy to hand over.  I have some ideas on how to leverage this.

**Comment by stelian42** [comment]
The time zone issue affected normally the Moon calculations, but only those in the "Calculations" tab, not those in the "Find body" dialog. But the difference was probably small, only the distance to the moon was wrongly calculated with the time zone offset, so I don't believe this distance evolves much in a couple of hours.

**Comment by rgleason** [comment]
Bob and Stelian,   I forwarded an email from Antoine that has two PDF attachments.  One of them may be very useful in giving you suggestions about this problem. The other is sort of disappointing, but I don't think it is a reason to stop this effort.On Mar 7, 2025 14:08, rbossert149419 ***@***.***> wrote:
  I just retested SD/HP using my Meeus algorithm spreadsheet where I had about a dozen examples of 2024, 2025, and some historic dates after 2001.  The purpose of that spreadsheet was to prove to me that the 1996 Meeus algorithm still worked (Celestial Tools program seemed to use it when I read some of it's code).  The examples matches both the algorithm and the Nautical Almanac for SD and HP.  I then checked 5 specific Jan 2025 dates on my Statistical Analysis spreadsheet (the spreadsheet has 49 random dates and times that spread evenly across 2025.  These numbers were slightly better than I reported last night.  5 dates (SD and HP) or 10 observations.  9 had 0 difference from Nautical Almanac.  Only 1 observation was off by .1  minute.
The 10 observations did not seem to improve GHA and Dec although I was comparing to nautical almanac which only has .1 minutes precision.  Perhaps the time zone didn't impact Lat/Lon position of the moon?
Any idea where the time zone issue would make an affect....Sun, Stars, Planets?  What issue have I missed testing?
Later on, I'll update my test scripts with actual results.  And will be very happy to hand over.  I have some ideas on how to leverage this.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>



rbossert149419 left a comment (rgleason/celestial_navigation_pi#25)
I just retested SD/HP using my Meeus algorithm spreadsheet where I had about a dozen examples of 2024, 2025, and some historic dates after 2001.  The purpose of that spreadsheet was to prove to me that the 1996 Meeus algorithm still worked (Celestial Tools program seemed to use it when I read some of it's code).  The examples matches both the algorithm and the Nautical Almanac for SD and HP.  I then checked 5 specific Jan 2025 dates on my Statistical Analysis spreadsheet (the spreadsheet has 49 random dates and times that spread evenly across 2025.  These numbers were slightly better than I reported last night.  5 dates (SD and HP) or 10 observations.  9 had 0 difference from Nautical Almanac.  Only 1 observation was off by .1  minute.
The 10 observations did not seem to improve GHA and Dec although I was comparing to nautical almanac which only has .1 minutes precision.  Perhaps the time zone didn't impact Lat/Lon position of the moon?
Any idea where the time zone issue would make an affect....Sun, Stars, Planets?  What issue have I missed testing?
Later on, I'll update my test scripts with actual results.  And will be very happy to hand over.  I have some ideas on how to leverage this.

**Comment by rbossert149419** [comment]
I'm going to fully update my statistical analysis spreadsheet and
re-summarize as "after change" findings.  It seems that there will be
interest in what we've worked on.  And, it will be useful to assess where
we are with all of the other bodies and most importantly, show
the improvement to the plug-in's calculation of Moon's position and the
other bodies after the Delta-T formula was fixed.

I'll send the spreadsheet (Exel format) when i'm done.

Bob

**Comment by rbossert149419** [comment]
By nature, I like to improve.  So maybe surprisingly, I was
encouraged equally by both attachments!  It showed interest.  It
showed skepticism.  Improving the precision like we are doing is the
foundation of the solution.  And then leveraging the visualization (charted
position, weather/clouds, etc) inherent to OpenCPN can lead to Celestial
Nav improvements beyond what stand alone sight reduction software like
"Celestial Navigation Tools" can do.

Since both attachments was about precision, can we move this discussion
under Statistical Analysis of how close GHA and Dec plus Semi-Diameter and
Horizontal Parallex is #49.  We use #49 for precision status.   And then
create issues for specific actions for specific improvements.

Meanwhile, i'll update my Statistical Analysis report and spreadsheet with
up-to-date Plugin GHA, Dec, SD, HP data.  That should give us an idea of
where we stand as of today.

Antoine had a lot of ideas to consider.  For me, one thing stood out.  It
was "Time-Distance, speed of light" for the moon should be considered.  I
seem to recall the Nautical Almanac includes it for GHA (and Dec).  Does
the plug in for the moon?  I suspect (not sure) it might be factored in as
part of Apparent Lambda (Lambda being the Longitude of the body in the
Ecliptic coordinate system, and Apparent refers to what we see) that Meeus
calculates.  I'll have to re-read that chapter in his book.  But, maybe
Stelian might see the variable in the code.

Thanks, Bob

**Comment by rgleason** [comment]
Bob can we close this, or should we leave it open until you do your report?

**Comment by stelian42** [comment]
My opinion on this is to close, and open specific tickets for the other problems.

**Comment by rgleason** [comment]
Yes.

**Comment by rbossert149419** [comment]
This can be closed
